name: nursery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  another_flushbar: ^1.12.30
  line_awesome_flutter: ^2.0.0
  animate_do: ^3.3.4
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  get: ^4.6.6
  flutter_lints: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^4.17.3
  loading_animation_widget: ^1.2.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  uuid: ^4.4.0
  multi_image_picker_plus: ^0.0.4
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  flutter_rating_bar: ^4.0.1
  flutter_vlc_player: ^7.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
