// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu6s0PbVRYYWXbiVX-v8MVs_3bEhodn8U',
    appId: '1:428006679025:web:209a840fd1064a1de9a450',
    messagingSenderId: '428006679025',
    projectId: 'nursery-f60a1',
    authDomain: 'nursery-f60a1.firebaseapp.com',
    storageBucket: 'nursery-f60a1.appspot.com',
    measurementId: 'G-NLCP6675RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxVvKVi05OUGP4AUcYlS-TW4u1nF2IIWs',
    appId: '1:428006679025:android:d972eed04bad5bcae9a450',
    messagingSenderId: '428006679025',
    projectId: 'nursery-f60a1',
    storageBucket: 'nursery-f60a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhyACsuD3mNZ3Bsx-otc89Kb6GW-hqVs',
    appId: '1:428006679025:ios:e7100f6f11fd1e8ee9a450',
    messagingSenderId: '428006679025',
    projectId: 'nursery-f60a1',
    storageBucket: 'nursery-f60a1.appspot.com',
    iosBundleId: 'com.example.nursery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhyACsuD3mNZ3Bsx-otc89Kb6GW-hqVs',
    appId: '1:428006679025:ios:e7100f6f11fd1e8ee9a450',
    messagingSenderId: '428006679025',
    projectId: 'nursery-f60a1',
    storageBucket: 'nursery-f60a1.appspot.com',
    iosBundleId: 'com.example.nursery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu6s0PbVRYYWXbiVX-v8MVs_3bEhodn8U',
    appId: '1:428006679025:web:e216e234a1d08a32e9a450',
    messagingSenderId: '428006679025',
    projectId: 'nursery-f60a1',
    authDomain: 'nursery-f60a1.firebaseapp.com',
    storageBucket: 'nursery-f60a1.appspot.com',
    measurementId: 'G-H02SKJTZH0',
  );
}
